# Generated by Django 5.2.2 on 2025-06-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profissionais",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome_social", models.CharField(max_length=100)),
                ("profissao", models.CharField(max_length=50)),
                ("endereco", models.CharField(max_length=200)),
                ("contato", models.CharField(max_length=11)),
            ],
        ),
    ]
