# Generated by Django 5.2.2 on 2025-06-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profissionais",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
