# Generated by Django 5.2.2 on 2025-06-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profissionais", "0002_profissionais_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profissionais",
            name="preco_consulta",
            field=models.IntegerField(default=80),
        ),
    ]
