# Generated by Django 5.2.2 on 2025-06-17 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendamentosConsultas",
            fields=[
                ("idConsulta", models.AutoField(primary_key=True, serialize=False)),
                ("dataConsulta", models.DateField()),
                ("nome_social_cliente", models.CharField(max_length=100)),
                ("comparecimento", models.BooleanField(default=False)),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profissionais.profissionais",
                    ),
                ),
            ],
        ),
    ]
