# Generated by Django 5.2.2 on 2025-06-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultas",
            name="nome_social_cliente",
            field=models.CharField(default="aa", max_length=100),
            preserve_default=False,
        ),
    ]
