# Generated by Django 5.2.2 on 2025-06-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agendamentosconsultas",
            old_name="dataConsulta",
            new_name="data_Consulta",
        ),
        migrations.RemoveField(
            model_name="agendamentosconsultas",
            name="idConsulta",
        ),
        migrations.AddField(
            model_name="agendamentosconsultas",
            name="consulta_ativa",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="agendamentosconsultas",
            name="hora_consulta",
            field=models.TimeField(default="17:50"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agendamentosconsultas",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
