# Generated by Django 5.2.2 on 2025-06-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultas",
            "0002_rename_dataconsulta_agendamentosconsultas_data_consulta_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamentosconsultas",
            name="hora_consulta",
        ),
        migrations.AlterField(
            model_name="agendamentosconsultas",
            name="data_Consulta",
            field=models.DateTimeField(),
        ),
    ]
