# Generated by Django 5.2.2 on 2025-06-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0003_remove_agendamentosconsultas_hora_consulta_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agendamentosconsultas",
            old_name="data_Consulta",
            new_name="data_consulta",
        ),
    ]
