# Generated by Django 5.2.2 on 2025-06-20 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0004_rename_data_consulta_agendamentosconsultas_data_consulta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamentosconsultas",
            name="data_consulta",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
