# Generated by Django 5.2.2 on 2025-06-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("consultas", "0005_alter_agendamentosconsultas_data_consulta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamentosconsultas",
            name="nome_social_cliente",
        ),
        migrations.AddField(
            model_name="agendamentosconsultas",
            name="cliente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="clientes.cadastroclientes",
            ),
            preserve_default=False,
        ),
    ]
