# Generated by Django 5.2.2 on 2025-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0006_remove_agendamentosconsultas_nome_social_cliente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamentosconsultas",
            name="comparecimento",
        ),
        migrations.AddField(
            model_name="agendamentosconsultas",
            name="status_consulta",
            field=models.CharField(
                choices=[
                    ("scheduled", "Agendada"),
                    ("confirmed", "Confirmada"),
                    ("canceled", "Cancelada"),
                    ("completed", "Realizada"),
                ],
                default="Agendada",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
