# Generated by Django 5.2.2 on 2025-06-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0007_remove_agendamentosconsultas_comparecimento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamentosconsultas",
            name="status_consulta",
            field=models.CharField(
                choices=[
                    ("agendada", "Agendada"),
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                    ("completa", "Realizada"),
                ],
                max_length=20,
            ),
        ),
    ]
