# Generated by Django 5.2.2 on 2025-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CadastroClientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_social", models.CharField(max_length=100)),
                ("cpf", models.IntegerField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contato", models.CharField(max_length=11)),
                ("logradouro", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=5)),
                ("complemento", models.CharField(max_length=200)),
                ("bairro", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=8)),
            ],
        ),
    ]
