# Generated by Django 5.2.2 on 2025-06-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastroclientes",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
