# Generated by Django 5.2.2 on 2025-06-29 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_alter_cadastroclientes_cpf"),
        ("consultas", "0008_alter_agendamentosconsultas_status_consulta"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagamentoDeConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo_de_pagamento",
                    models.CharField(choices=[("pix", "PIX"), ("boleto", "Boleto")]),
                ),
                (
                    "status_pagamento",
                    models.CharField(
                        choices=[("pendente", "pendente"), ("pago", "pago")]
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cadastroclientes",
                    ),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultas.agendamentosconsultas",
                    ),
                ),
            ],
        ),
    ]
