# Generated by Django 5.2.2 on 2025-06-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_pagamentodeconsulta"),
        ("consultas", "0008_alter_agendamentosconsultas_status_consulta"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PagamentoDeConsulta",
            new_name="PagamentoConsulta",
        ),
    ]
