# Generated by Django 5.2.2 on 2025-06-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_rename_pagamentodeconsulta_pagamentoconsulta"),
        ("consultas", "0008_alter_agendamentosconsultas_status_consulta"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PagamentoConsulta",
            new_name="PagamentoConsultas",
        ),
    ]
