# Generated by Django 5.2.2 on 2025-06-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_rename_pagamentoconsulta_pagamentoconsultas"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamentoconsultas",
            name="preco_consulta",
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pagamentoconsultas",
            name="metodo_de_pagamento",
            field=models.CharField(
                choices=[("pix", "PIX"), ("boleto", "Boleto")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="pagamentoconsultas",
            name="status_pagamento",
            field=models.CharField(
                choices=[("pendente", "pendente"), ("pago", "pago")], max_length=20
            ),
        ),
    ]
