# Generated by Django 5.2.2 on 2025-06-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0007_cadastroclientes_asaas_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamentoconsultas",
            name="data_vencimento",
            field=models.DateField(null=True),
        ),
    ]
