# Generated by Django 5.2.2 on 2025-06-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0008_pagamentoconsultas_data_vencimento"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamentoconsultas",
            name="asaas_payment_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
