# Generated by Django 5.2.2 on 2025-07-01 14:27

import clientes.validador_cpf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0010_alter_pagamentoconsultas_metodo_de_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastroclientes",
            name="cpf",
            field=models.CharField(
                help_text="Pode ser digitado com ou sem pontuação.",
                max_length=14,
                unique=True,
                validators=[clientes.validador_cpf.validar_cpf],
            ),
        ),
    ]
