name: CI/CD and deploy
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: quality assurance
    runs-on: ubuntu-lastest
    container: python:3.12.11

    Serices:
      db:
        image: postgres:14
        env:
          POSTGRES_DB: myapp
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

steps: 
  - uses: actions/checkout@v2


  - name: Install Poetry
    uses: abatilo/actions-poetry@v2.0.0
    with:
      poetry-version: 1.4.2

  - name: Install Dependencies
    run: make install && make install-pre-commit


  - name: Lint
    run: make lint

  - name: Test
    run: make test
    env:
      DATABASE_HOST: db  



          